const {src, dest, watch, series, parallel} = require('gulp');
const sass                                 = require('gulp-sass')(require('sass'));
const postcss                              = require('gulp-postcss');
const autoprefixer                         = require('autoprefixer');
const cssnano                              = require('cssnano');
const sourcemaps                           = require('gulp-sourcemaps');
const rename                               = require('gulp-rename');
const terser                               = require('gulp-terser');
const concat                               = require('gulp-concat');
const imagemin                             = require('gulp-imagemin');
const header                               = require('gulp-header');
const {generate: generateCritical}         = require('critical');
const fs                                   = require('fs');
const postcssLib                           = require('postcss');

// ---------------------------------------------------------------------------
// Banners
// ---------------------------------------------------------------------------

const cssBanner = `/*
DO NOT EDIT THIS FILE DIRECTLY.
Generated via Gulp. Changes will be overwritten.
Edit SCSS in /assets/scss/ instead.
*/
\n`;

const jsBanner = `/*
Compiled file. Do not edit directly.
Edit source in /assets/js/src/
*/
\n`;

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const paths = {
  scss  : { watch: './assets/scss/**/*.scss' },
  js    : { src: './assets/js/src/**/*.js', dest: './assets/js' },
  images: { src: './assets/images/**/*.{jpg,jpeg,png,gif,svg}', dest: './assets/images' },
  css   : { dest: './assets/css' },
};

const cssnanoOptions = {
  preset: ['default', { discardComments: { removeAll: true }, uniqueSelectors: true }]
};

// ---------------------------------------------------------------------------
// CSS helpers
// ---------------------------------------------------------------------------

function buildCSS(file, outName, isDev = false) {
  const plugins = isDev ? [autoprefixer()] : [autoprefixer(), cssnano(cssnanoOptions)];

  return function compile() {
    let stream = src(file).pipe(sourcemaps.init());

    stream = stream
      .pipe(sass().on('error', sass.logError))
      .pipe(postcss(plugins))
      .pipe(header(cssBanner))
      .pipe(rename(outName));

    if (isDev) {
      stream = stream.pipe(sourcemaps.write('.'));
    }

    return stream.pipe(dest(paths.css.dest));
  };
}

// ---------------------------------------------------------------------------
// CSS entry points
// Add a new page: create assets/scss/pages/{slug}.scss and add an entry here.
// ---------------------------------------------------------------------------

const cssEntries = [
  ['./assets/scss/main.scss',                    'style.min.css'],
  ['./assets/scss/pages/home.scss',              'home.min.css'],
  ['./assets/scss/pages/contact.scss',           'contact.min.css'],
  ['./assets/scss/pages/maintenance-plan.scss',  'maintenance-plan.min.css'],
  ['./assets/scss/pages/blog.scss',              'blog.min.css'],
  ['./assets/scss/pages/thank-you.scss',         'thank-you.min.css'],
  ['./assets/scss/pages/lennox-ultimate-comfort-system.scss', 'lennox-ultimate-comfort-system.min.css'],
];

const stylesBuild = parallel(...cssEntries.map(([file, out]) => buildCSS(file, out, false)));
const stylesDev   = parallel(...cssEntries.map(([file, out]) => buildCSS(file, out, true)));

// ---------------------------------------------------------------------------
// JS
// ---------------------------------------------------------------------------

function buildJS(isDev = false) {
  return function scripts() {
    return src([paths.js.src])
      .pipe(concat('main.js'))
      .pipe(isDev ? sourcemaps.init() : terser())
      .pipe(header(jsBanner))
      .pipe(dest(paths.js.dest));
  };
}

const scriptsBuild = buildJS(false);
const scriptsDev   = buildJS(true);

// ---------------------------------------------------------------------------
// Images
// ---------------------------------------------------------------------------

function optimizeImages() {
  return src(paths.images.src, {allowEmpty: true})
    .pipe(imagemin([
      imagemin.gifsicle({interlaced: true}),
      imagemin.mozjpeg({quality: 80, progressive: true}),
      imagemin.optipng({optimizationLevel: 5}),
      imagemin.svgo({plugins: [{removeViewBox: false}, {cleanupIDs: false}]}),
    ]))
    .pipe(dest(paths.images.dest));
}

// ---------------------------------------------------------------------------
// Critical CSS
// ---------------------------------------------------------------------------

// Update SITE_URL to match your Local by Flywheel dev URL.
const SITE_URL = 'https://staging.orzechheating.local/';

// Pages to extract critical CSS from. Add slugs as needed.
const CRITICAL_PAGES = [
  '/',
  '/lennox-ultimate-comfort-system',
  '/maintenance-plan',
  '/air-conditioner-installation',
  '/financing',
  '/essential-furnace-buying-guide',
  '/ultimate-ac-buying-guide',
  '/emergency-hvac-repair',
  '/quote-form',
  '/heat-pumps',
  '/furnace-and-air-conditioner-deals',
  '/news-and-blog',
  '/clean-home-initiative',
  '/terms-and-conditions',
  '/sales-form',
  '/rooftop-services',
  '/air-conditioning',
  '/boiler-services',
  '/ductless-air-conditioner-installation',
  '/rooftop-hvac-installation',
  '/rooftop-hvac-repair',
  '/boiler-repair',
  '/refrigeration-replacement',
  '/refrigeration-repair',
  '/leaking-pipes',
  '/frozen-burst-pipe-repair-replacement',
  '/drain-cleaning',
  '/kitchen-bathroom',
  '/water-lines',
  '/air-conditioner-repair',
  '/sump-pumps',
  '/rooftop-hvac-replacement',
  '/boiler-replacement',
  '/air-conditioner-replacement',
  '/refrigeration-installation',
  '/central-air-conditioners',
  '/boiler-installation',
  '/ductwork-installation',
  '/armstrong-air-products',
  '/thermostats',
  '/boilers',
  '/forced-air-furnaces',
  '/erv-hrv',
  '/humidifiers',
  '/gas-fireplaces',
  '/ductless-air-conditioners',
  '/lennox-products',
  '/plumbing-repairs',
  '/pool-heater',
  '/furnace-replacement',
  '/furnace-installation',
  '/contact-us',
  '/furnace-repair',
  '/faqs',
  '/about'
];

const CRITICAL_OPTIONS = {
  dimensions: [
    {width: 375,  height: 812},   // mobile
    {width: 768,  height: 1024},  // tablet
    {width: 1440, height: 900},   // desktop
  ],
  inline  : false,
  ignore  : {atrule: ['@font-face']},
  request : {https: {rejectUnauthorized: false}},
  penthouse: {
    chromiumFlags: ['--ignore-certificate-errors'],
    chromePath   : '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    timeout      : 90000,
  },
};

async function critical() {
  for (const page of CRITICAL_PAGES) {
    const path = typeof page === 'object' ? page.path : page;
    const slug = typeof page === 'object' ? page.slug : (page === '/' ? 'home' : page.replace('/', ''));
    console.log(`  → Extracting critical CSS for: ${slug}`);

    const cssFiles = ['assets/css/style.min.css'];
    const pageCss  = `assets/css/${slug}.min.css`;
    if (fs.existsSync(pageCss)) {
      cssFiles.push(pageCss);
    }

    const {css} = await generateCritical({
      ...CRITICAL_OPTIONS,
      src: SITE_URL + path,
      css: cssFiles,
    });

    const result = await postcssLib([cssnano(cssnanoOptions)]).process(css, {from: undefined});
    fs.writeFileSync(`assets/css/critical-${slug}.min.css`, result.css);
  }
}

// Copy LoadCSS polyfill from node_modules to assets/js
function copyLoadCSS() {
  return src('./node_modules/fg-loadcss/dist/cssrelpreload.js')
    .pipe(terser())
    .pipe(rename('cssrelpreload.min.js'))
    .pipe(dest(paths.js.dest));
}

// ---------------------------------------------------------------------------
// Watcher
// ---------------------------------------------------------------------------

function watcher() {
  watch(paths.scss.watch, stylesDev);
  watch(paths.js.src, scriptsDev);
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

exports.styles   = stylesBuild;
exports.scripts  = scriptsBuild;
exports.images   = optimizeImages;
exports.critical = critical;

// gulp dev  — compile with source maps, then watch for changes
exports.dev = series(parallel(stylesDev, scriptsDev, copyLoadCSS), watcher);

// gulp build — full production pipeline (minified, optimised)
exports.build = parallel(stylesBuild, scriptsBuild, optimizeImages, copyLoadCSS);

// default: production build + watch
exports.default = series(exports.build, watcher);
