<?php

/**
 * Inline critical CSS and load stylesheets asynchronously.
 *
 * - critical.min.css (and per-page variants) are generated by `gulp critical`.
 * - That file is inlined into <head> so the browser renders immediately.
 * - Stylesheets are then loaded async via the preload pattern + noscript fallback.
 *
 * To regenerate: run `gulp critical` with the local dev site running.
 * Falls back to standard load when no critical CSS file exists.
 */
add_action( 'wp_head', function () {
  if ( is_front_page() ) {
    $slug = 'home';
  } else {
    $slug = get_post_field( 'post_name', get_the_ID() );
  }

  $critical_file = get_stylesheet_directory() . "/assets/css/critical-{$slug}.min.css";

  // Fall back to global critical.min.css if page-specific file doesn't exist
  if ( ! file_exists( $critical_file ) ) {
    $critical_file = get_stylesheet_directory() . '/assets/css/critical.min.css';
  }

  if ( file_exists( $critical_file ) ) {
    echo '<style id="orzech-critical-css">' . file_get_contents( $critical_file ) . '</style>' . "\n";
  }

  // Inline the LoadCSS polyfill so async stylesheet loading works in all browsers
  $polyfill_path = get_stylesheet_directory() . '/assets/js/cssrelpreload.min.js';
  if ( file_exists( $polyfill_path ) ) {
    echo '<script id="loadcss-polyfill">' . file_get_contents( $polyfill_path ) . '</script>' . "\n";
  }
}, 2 );

/**
 * Convert theme stylesheets to async preload when critical CSS is active.
 * Targets the main style.css and all orzech-prefixed page handles.
 */
add_filter( 'style_loader_tag', function ( $html, $handle ) {
  $is_target = ( $handle === 'orzech-child-style' || strpos( $handle, 'orzech-' ) === 0 );

  if ( ! $is_target ) {
    return $html;
  }

  $async = str_replace(
    "rel='stylesheet'",
    "rel='preload' as='style' onload=\"this.onload=null;this.rel='stylesheet'\"",
    $html
  );

  return $async . '<noscript>' . $html . '</noscript>' . "\n";
}, 10, 2 );
